version: '3.1'
services:
  uuid-service-sso:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-service-sso:1.0.0
    container_name: uuid-service-sso
    ports:
      - 1111:1111
    restart: always

networks:
  default:
    external:
      name: uuid_net