version: '3.1'
services:
  uuid-service-admin:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-service-admin:1.0.0
    container_name: uuid-service-admin
    ports:
      - 8001:8001
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 450M

networks:
  default:
    external:
      name: uuid_net