version: '3.1'
services:
  uuid-service-topic:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-service-topic:1.0.0
    container_name: uuid-service-topic
    ports:
      - 9005:9005
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 450M

networks:
  default:
    external:
      name: uuid_net