version: '3.1'
services:
  uuid-config-1:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-config:1.0.0
    container_name: uuid-config-1
    ports:
      - 8888:8888
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 180M

#  uuid-config-2:
#    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-config:1.0.0
#    container_name: uuid-config-2
#    ports:
#      - 8889:8888
#    restart: always

networks:
  default:
    external:
      name: uuid_net