version: '3.1'
services:
  uuid-service-common:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-service-common:1.0.0
    container_name: uuid-service-common
    ports:
      - 9000:9000
    restart: always

networks:
  default:
    external:
      name: uuid_net