version: '3.1'
services:
  uuid-eureka-1:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-eureka:1.0.0
    container_name: uuid-eureka-1
    ports:
      - 8761:8761
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 180M

#  uuid-eureka-2:
#    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-eureka:1.0.0
#    container_name: uuid-eureka-2
#    ports:
#      - 8889:8888
#    restart: always

networks:
  default:
    external:
      name: uuid_net