version: '3.1'
services:
  uuid-service-comment:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-service-comment:1.0.0
    container_name: uuid-service-comment
    ports:
      - 9003:9003
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 350M

networks:
  default:
    external:
      name: uuid_net