version: '3.1'
services:
  uuid-gateway:
    image: registry.cn-shenzhen.aliyuncs.com/uuid/uuid-gateway:1.0.0
    container_name: uuid-gateway
    ports:
      - 8000:8000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M

networks:
  default:
    external:
      name: uuid_net